version: '2.0'
services:
  db:
    image: mariadb
    container_name: seafile-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=Y5&8#TGApti7%7ymu^8^tkvLD6XRPShT
      - MYSQL_LOG_CONSOLE=true
    volumes:
      - ./data/mariadb:/var/lib/mysql

  memcached:
    image: memcached
    container_name: seafile-memcached
    entrypoint: memcached -m 256
          
  seafile:
    image: seafileltd/seafile-mc
    container_name: seafile
    ports:
      - "9060:80"
    volumes:
      - ./data/app:/shared
    environment:
      - DB_HOST=db
      - DB_ROOT_PASSWD=Y5&8#TGApti7%7ymu^8^tkvLD6XRPShT
      - TIME_ZONE=Etc/UTC
      - SEAFILE_ADMIN_EMAIL=jeff.boesenkool@gmail.com
      - SEAFILE_ADMIN_PASSWORD=rgmBL4#xWaEAPb!zrBTYPZqoEmBVnae&
      - SEAFILE_SERVER_LETSENCRYPT=false
      - SEAFILE_SERVER_HOSTNAME=seafile.elpatron.dev
    depends_on:
      - db
      - memcached

networks:
  default:
    external:
      name: nginxproxymanager
