version: "3.8"

services:
  uptimekuma:
    container_name: uptimekuma
    image: louislam/uptime-kuma:latest
    ports:
      - 9021:3001
    volumes:
      - data:/app/data

volumes:
  data:

networks:
  default:
    external:
      name: nginxproxymanager
