version: "3.8"

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: development
    ports:
      - 9023:27017
    volumes:
      - data:/data/db

volumes:
  data:

networks:
  default:
    external:
      name: nginxproxymanager
