version: "3.8"

services:
  portainer:
    container_name: portainer-ce
    image: portainer/portainer-ce:latest
    command: -H unix:///var/run/docker.sock
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:

networks:
  default:
    external:
      name: nginxproxymanager
