version: "2.1"
services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000100
      - PGID=1000100
      - TZ=Europe/Amsterdam
      - SERVERURL=IPv4_ONLY!!!!!
      - SERVERPORT=51820
      - PEERS=4
      - PEERDNS=auto
    volumes:
      - ./config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

networks:
  default:
    name: default_network
